version: '3'

services:
  code_style:
    build: docker/code_style
    volumes:
      - .:/src
      - ./code_style.sh:/code_style.sh:ro
    command: ["/bin/sh", "/code_style.sh", "/src"]

  snap_build:
    image: snapcore/snapcraft:edge
    volumes:
      - .:/src
    working_dir: /src/dist/snap
    command: ["/bin/sh", "-c", "set -ex; apt-get update -y; for d in daemon gtk qt utils; do cd $$d; ERR=0; snapcraft || ERR=$$?; chown -R $$(stat -c '%u:%g' .) .; [ $$ERR -eq 0 ] || exit $$ERR; mv *.snap ..; cd ..; done"]
